apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://node:21-alpine3.17
        name: Build
        kind: build
        shell: sh
        run: npm run compile
